-- create tablespaces
-- CREATE TABLESPACE INDEX_MAKER_D DATAFILE 'tbs_indexmaker_d.dat' SIZE 10M REUSE AUTOEXTEND ON NEXT 10M;
-- CREATE TABLESPACE INDEX_MAKER_I DATAFILE 'tbs_indexmaker_i.dat' SIZE 10M REUSE AUTOEXTEND ON NEXT 10M;

-- create user and add all privileges
-- CREATE USER "INDEX_MAKER" DEFAULT IDENTIFIED BY Start_2013;
-- GRANT ALL PRIVILEGES TO "INDEX_MAKER" IDENTIFIED BY Start_2013;

-- create tables and indexes
---- ROW_CONTENT
CREATE TABLE ROW_CONTENT
  (
    ID         NUMBER(9,0) NOT NULL,
    FIRST_CELL VARCHAR2(255 BYTE) NOT NULL
  );
--    TABLESPACE INDEX_MAKER_D;
-- --
-- ALTER TABLE "INDEX_MAKER"."ROW_CONTENT" ADD CONSTRAINT "PK_ROW_CONTENT" PRIMARY KEY ("ID")  using index TABLESPACE INDEX_MAKER_I;
